name: updater
description: A tool to update The Mega App on Windows.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  archive: ^3.6.1
  path: ^1.9.0
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
